alert-level-announcement = Uwaga! Stan alarmowy stacji jest teraz { $name }! { $announcement }
alert-level-unknown = Unknown.
alert-level-unknown-instructions = Unknown.
alert-level-green = Zielony
alert-level-green-announcement = Możecie już bezpiecznie powrócić do miejsc pracy.
alert-level-green-instructions = Wykonaj swoją pracę.
alert-level-blue = Niebieski
alert-level-blue-announcement = Potwierdzono zagrożenie dla stacji. Ochrona powinna przeprowadzać wyrywkowe kontrole. Członkom załogi zaleca się zachowanie czujności i zgłaszanie podejrzanych działań ochronie.
alert-level-blue-instructions = Zaleca się, aby członkowie załogi zachowali czujność i zgłaszali podejrzane działania służbom ochrony.
alert-level-red = Czerwony
alert-level-red-announcement = Istnieje bezpośrednie zagrożenie dla stacji. Ochrona powinna być przygotowana do użycia siły śmiercionośnej, jeśli zajdzie taka potrzeba. Członkowie załogi powinni znaleźć bezpieczne schronienie i powinni stosować się do wszelkich obowiązujących poleceń władz.
alert-level-red-instructions = Członkowie załogi powinni znaleźć bezpieczne miejsce, w którym będą mogli się schronić, i proszeni są o stosowanie się do obowiązujących poleceń władz.
alert-level-violet = Fioletowy
alert-level-violet-announcement = Na stacji panuje zagrożenie wirusowe. Personel medyczny jest proszony o izolację członków załogi z objawami. Członkom załogi zaleca się zachowanie dystansu społecznego i stosowanie środków bezpieczeństwa w celu zapobiegania dalszemu rozprzestrzenianiu się wirusa.
alert-level-violet-instructions = Członkom załogi zaleca się zachowanie dystansu społecznego i stosowanie środków bezpieczeństwa w celu zapobiegania dalszemu rozprzestrzenianiu się wirusa.
alert-level-yellow = Żółty
alert-level-yellow-announcement = Na terenie stacji występuje zagrożenie strukturalne lub atmosferyczne. Personelowi technicznemu zaleca się natychmiastową reakcję i podjęcie środków bezpieczeństwa. Członkom załogi zaleca się unikanie zagrożenia i pozostanie w miejscu pracy, jeśli to konieczne.
alert-level-yellow-instructions = Członkom załogi zaleca się, aby trzymali się z dala od zagrożenia, a w razie konieczności pozostali w swoich miejscach pracy.
alert-level-gamma = Gamma
alert-level-gamma-announcement = Dowództwo Centralne wydało rozkaz wprowadzenia na stacji poziomu bezpieczeństwa Gamma. Służby bezpieczeństwa mają mieć broń stale przygotowaną, a wszyscy cywile mają natychmiast udać się do najbliższego miejsca, aby przetransportować ich w bezpieczne miejsce.
alert-level-gamma-instructions = Wszyscy cywile mają natychmiast udać się do najbliższego miejsca, aby zostać przetransportowani w bezpieczne miejsce.
alert-level-delta = Delta
alert-level-delta-announcement = Stacja jest obecnie zagrożona nieuchronnym zniszczeniem. Załodze zaleca się słuchanie przełożonych, aby uzyskać więcej informacji.
alert-level-delta-instructions = Zaleca się, aby członkowie załogi słuchali przełożonych, aby uzyskać więcej informacji.
alert-level-epsilon = Epsilon
alert-level-epsilon-announcement = Dowództwo Centralne wydało nakaz wprowadzenia na stacji poziomu bezpieczeństwa Epsilon. Należy rozważyć rozwiązanie wszystkich umów. ORAZ UDAĆ SIE DO SCHRONU
alert-level-epsilon-instructions = Rozważ rozwiązanie wszystkich umów. UDAJ SIE DO SCHRONU NATYCHMIAST
